apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploadimg-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /data/uploadimg-pv

