variables:
  FOLDER_NAME: "web"
  DOCKER_IMAGE: "zihrueiliou/web:v4.0.0"
stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
    - docker rmi $DOCKER_IMAGE
  only:
    - main
  tags:
    - docker-runner

deploy_job:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y sshpass
  script:
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p 22 $SSH_NAME  "kubectl set image deployment/$FOLDER_NAME $FOLDER_NAME=$DOCKER_IMAGE"
  only:
    - main
  tags:
    - docker-runner